---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky
  - cloudflare-ddns
  - coredns
  # - external-dns
  # - internal-dns
  - secret-reflector
  - traefik
  - wildcard-certificate
