---

- name: calico | deploy tigera operator to k3s manifest directory
  run_once: true
  ansible.builtin.get_url:
    url: "{{ calico.operator_manifest }}"
    dest: "{{ k3s_server_manifests_dir }}/tigera-operator.yaml"
    mode: 0644

- name: calico | deploy configuration to k3s manifest directory
  run_once: true
  ansible.builtin.template:
    src: "calico-installation.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-installation.yaml"
    mode: 0644

- name: calico | deploy BGP-peer to k3s manifest directory
  run_once: true
  ansible.builtin.template:
    src: "calico-bgppeer.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-bgppeer.yaml"
    mode: 0644
  when:
  - calico.bgp.enabled is defined
  - calico.bgp.enabled

- name: calico | deploy BGP-configuration to k3s manifest directory
  run_once: true
  ansible.builtin.template:
    src: "calico-bgpconfiguration.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-bgpconfiguration.yaml"
    mode: 0644
  when:
  - calico.bgp.enabled is defined
  - calico.bgp.enabled
