---

- name: kubeconfig | copy config file to /tmp
  run_once: true
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "{{ inventory_dir | dirname | dirname | dirname | dirname }}/kubeconfig"
    owner: "{{ lookup('env', 'USER') }}"
    flat: true
  when:
  - k3s_control_node is defined
  - k3s_control_node

- name: kubeconfig | update kubeconfig with the right IPv4 address
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "{{ inventory_dir | dirname | dirname | dirname | dirname }}/kubeconfig"
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ k3s_registration_address }}:6443'
