---

- name: secrets | load etcd ca
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt"
  register: slurped_etcd_ca_file

- name: secrets | load etcd cert
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-client.crt"
  register: slurped_etcd_cert_file

- name: secrets | load etcd cert key
  run_once: true
  slurp:
    src: "/var/lib/rancher/k3s/server/tls/etcd/server-client.key"
  register: slurped_etcd_cert_key_file

- name: secrets | deploy manifests
  run_once: true
  ansible.builtin.copy:
    mode: 0644
    content: |
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: networking
      ---
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: coredns-etcd
        namespace: networking
      data:
        ca.crt: "{{ slurped_etcd_ca_file.content }}"
        cert.pem: "{{ slurped_etcd_cert_file.content }}"
        key.pem: "{{ slurped_etcd_cert_key_file.content }}"
    dest: "{{ k3s_server_manifests_dir }}/coredns-etcd-secret.yaml"
