---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-galera
  namespace: databases
spec:
  releaseName: mariadb-galera
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb-galera
      version: 5.7.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb-galera
      tag: 10.5.10-debian-10-r0
      pullPolicy: IfNotPresent
      debug: true
    clusterDomain: cluster.local
    rootUser:
      user: root
      password: ""
      forcePassword: false
    existingSecret: mariadb-galera-creds
    galera:
      name: galera
      bootstrap:
        bootstrapFromNode:
        forceSafeToBootstrap: false
      mariabackup:
        user: mariabackup
        password: ""
        forcePassword: false
    persistence:
      enabled: true
      mountPath: /bitnami/mariadb
    configurationConfigMap: mariadb-galera-conf
    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mysqld-exporter
        tag: 0.12.1-debian-10-r430
        pullPolicy: IfNotPresent
    replicaCount: 3
