# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-galera-creds
    namespace: databases
stringData:
    mariadb-galera-mariabackup-password: ENC[AES256_GCM,data:pQmUgTZAzV1yIsm4G4QUDLqj3cDNd/Og,iv:BnWnmbc08dHA/mVwAYzdnR61+jOcvExCBq5Sw2VbZt8=,tag:GpkG58FZO+Es4vewNEcufA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:LCzSkRYcOAghtHpzAzyfyG0eYHxUEI1t,iv:A2sZqSAOqEhfrDtVTnDSs92pVrFsKkdiyi7YDNhMFlw=,tag:ug/t0NN4Po3MH9UzYU0loQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:5u8AVULcC4Lh5R4HNnF7jthhcvYP2Mr4,iv:hJmXtVyg7VerMn7jlpjqwDwEUqO7a/pOHL166QV9UOI=,tag:HsrRRHgB+6JND8kvP9UlgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-09T07:00:00Z"
    mac: ENC[AES256_GCM,data:Pw2g5AvjE41mg33zpyi/mABT/EUMOJoIDtV4iNi+nKOkvaUSF/m/sXpQwi9v2F+a2s1RmX5qf6X82Ph89Tb4Sy5ZgdOvN8Py0xZCA0sIrkVYl5W5b/WfFHXmsozKwVbhQzkOXhqAKDM+dPT6iK45a46Z2qoSFls9V9wzhnHEh9c=,iv:EPg+ZtIP8nXjgBiOlOBe76o0gRtIaZ0Mecn27vEzeHM=,tag:+AQxWIRfPtq/0+HR6VKwRg==,type:str]
    pgp:
        - created_at: "2021-05-09T06:59:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/0I6bEV8DNNAQ//TWQMfyhzkr+G7al91HvKpCpBK2UyovDIJvAULIXCtJv/
            hLhoqMrEPHGovUWC7+GKB1vQ2/eTz4/kb7zZzxS9urXfAQqDZoVmqdUd2Xj25vfN
            7bieQqPGbIAhVwxqjZ6Mng16EJh05qb19ZSvv8BNzHcU/ax1y6D8RADhQx8ab6mI
            D5NyzJmPmL48SSrLxc1XeVKGoWzHrt64CqEu+x6RxQsd/fwird+azKxNV1/EtSB0
            L+jSdQNHW9aMWuN43jSaAuwzZ/ivVz/Vcp0UEAA5m4iDQTYClD73OlFapqAWzeCk
            pJ2yyAhMacLJuATzTp8IgsoXjNiOAXer+xreti8Ts4lrnkVknEY+TpFsHpcrVNQd
            Fhpv0KNFYpnyloyL0OCZh8AyX+RxgoFhkpYrFy7XWifjxI9GeDG1/KFMaD5wYHBW
            iQGSQ6s5B5oNSlAdBGYhDnsWaPopayfruvURP8u0GpCHgzIDYhWdAMbAXVeHxLy+
            TdkOhIOKztXAxKn9rlnjxjgWDE/2xQD7hZswVqgZQEjo15TGA0EW/OIWSuOFFfap
            BUerUnWF+oJNXmxR4fQXTZTYj+hQatkwo3FULd2zaRyGfMxcYxOXqDXUi5N8JSC9
            2yzjelqd4h1UcVdgsHvrMJir/Hdl/QxKt1S4pSeGV+0u0Ko/dapoJU9rBX8xgDnS
            XAEmZoPQxqbLUHFVJsmJMpdeo+EUzjOle8Zq+mDrpCS+YfB8MXdU1N+0vy1Q49Jv
            LXFMWHxWwDnfxmoKEwH0ao2OBkwy46vYKvLP+UyNfxaLr37JFmk8wjYNpfve
            =8Vfj
            -----END PGP MESSAGE-----
          fp: 84680C43E8FBE3DBA9468BD330D9BD1C5E315159
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
