# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-galera-creds
    namespace: databases
stringData:
    MARIADB-ROOT-PASSWORD: ENC[AES256_GCM,data:cWR8QLRE+Hv6XN1yPyxCa4Tk,iv:NQOU1GmHZKBeaD4Ev5UohIbNVxOe93B1OK8tg1fltiQ=,tag:IzQZMyW9NL/7Ylarc0LEgA==,type:str]
    MARIADB-GALERA-MARIABACKUP-PASSWORD: ENC[AES256_GCM,data:8uJ9Zkp7F39UaldgPhAuzIRF,iv:x7wNg4x5ldn1NTXxB1586d+F5FjIrFRHTm0nyd+W7aU=,tag:/JKARVzIf5JK8WUeyHvdQw==,type:str]
    MARIADB-PASSWORD: ENC[AES256_GCM,data:oMPYgaBYLfHibx1xpeXT2KKJ,iv:vg8oZTmlep9cIsxxxRmy2JO1OBRLrnkzLLpYtiMklb8=,tag:N4DL/EH393WxY1uew73wAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-08T16:02:56Z"
    mac: ENC[AES256_GCM,data:kDl4RKceIi61kjDo6+HUs6a7j4Zs6RahDAGLSrwROnZgH8kB3nfemrY6O71Pb3uSySuFQS5W/EBH1oCRY4VzbIVzy9mChGKJTjKcK8fqLP/nxAwujDR+rvsMXpPU6EDLk6OBlN0JFhH50DBwQKdd6P5OpLY8tfumxRACrxmcX8c=,iv:wF0WVfX+8fFKfR/C9lyKUXjovhKGt8Na3uWcWDB/c9k=,tag:A6XDeLf/Gnf7A8OVk0GgXg==,type:str]
    pgp:
        - created_at: "2021-05-08T16:02:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/0I6bEV8DNNAQ//cwpJwQpwnaboxf4wPOeICxop6SiCgPxeiBbEUjxGMy7m
            DerItBKhY33Kl9wnzma95nkTY5E6ekALTuSzjwtrhjw8cqEfb4mI/rmJadf+t1ts
            YSLOpejdhK7wdRwAuhmh169/6odcdWKvJJ46yb0svkZiYfxgr5sCsBDDr1LeGDot
            jlW4J7ryHpiJuoDP87wwkuftkYz4C4MYz0qv99dRl0JyYlhjkmSS9pEKMy8KCR5j
            BVs8o32AlvzMlZtQScnQNNLHpGnbJH+u6q0ll+7AvRSal/gKi5/VOywfRFKOUa/h
            yPN+4ilpM7lvIAOKqVh/0SwAp7rgNd6T8IrgEhEmx15GSH+0AupT71jq8O/8ef+m
            5/tOxJFU8DT8bAthsY55f7mKOCP9C70f5RW1PW3x1/DFJlfMTjoYApdecSqRMyOo
            qe8fnDAFWVEj2Fnmf42L30WrPQAzlM1SOVAWrBt4EoKN3Leeykx+gBHA3RAvFYlU
            NtoDfbxjs+LOuZCqM+Icd53p10ufUTwIadtaJQtqQ7MfNVdrwlALBepxMRyv9eYk
            LXpDTomNzilaJzgSWp3RNwHKLMa2QdaXrCH9FigfVVS61sxnlw7kTM6wIXjWYqDu
            GY01STJ6zQYE8i9H3ImHC9TYNvd2S2fEakg0X3qj/CmINFZekTWLEC76T02Xh5fS
            XgE4wFHl8qiC7tNTRjvQ04U8/CxDKSYJSHSSt2vR4cmY8tU0jdnx2hEa2/fS/S5o
            EBJ8b/9g1Shij5RWzrcGfimiEsBWV9TEFyHU1Ly7VFsCnE3K64XXxL8pdwmRKOA=
            =4Vuz
            -----END PGP MESSAGE-----
          fp: 84680C43E8FBE3DBA9468BD330D9BD1C5E315159
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
