# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-galera-creds
    namespace: databases
stringData:
    mariadb-galera-mariabackup-password: ENC[AES256_GCM,data:5+vE3klMJwVPwkcy0cZGIZgvSYuvfMFy,iv:rw0maC1HkWbnin/yTiSJxYmtOTWlYAlTKqtPg9c1wiY=,tag:cxzxR+TegBhNCkddx3qzvg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:YCGKQdaWhuBbrAnBODmLcZWR8DpBh06B,iv:l78vXk/c0J1PMyTyx6sEXzo383SjUJq4oNZRmWboxcU=,tag:jnASGsnRp/BUqZO40JT8Ug==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:TC6/YO6+Bipf4FSRx4UuXWWz9OT9BC8v,iv:9Fh+2WW1eMmPgq//UJ+VfMFNoWRbf7Z4VwXTzFm/AIQ=,tag:ew+rjxaxIxDXqTBvjwbaYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-08T17:09:15Z"
    mac: ENC[AES256_GCM,data:32ASRPkHc24wPDpfn9UG2bFp8elPsAlkPQ7Ub5U8XUeGSWn9quFaYz/DmLvBBdw6kvWpXg7JeMiyhngiIjZ3KDmHCCZKaeGLNGQzWcUGClUEuPZc+55S22LTkpJ7NAMi1pnS3nYoFpQ3pmO1ytWbagYH26kU0pUB0kx7Wm9lUtw=,iv:OWBOSdsb7cd7I1zlEWkw7MKHZwHcQkm1mFwITybS6jk=,tag:uGXHIgj7cOUADBkOpAbFyw==,type:str]
    pgp:
        - created_at: "2021-05-08T17:09:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/0I6bEV8DNNAQ/+JJAdkXcwn5E8eaKSCQs4qIqKrw1cfIpn4LjQTzSpBgrr
            Jzj8BgYhkNVCO2zTEBD0f4N89xouM7Zw5EWOBEShBXBQ41qCOqM5lV4jkwl4UWrk
            J5K/pS+xtUMJYJg9CEwuqOXuGPITLbLTbPvAUov4JeYSE7rbgXih5dfv4StDzYeA
            MPXH2iqveKL8l6lDiCziQvqy+9Yz7C17FlozRNZmcVaZg2PanEGlouydMuKvQC13
            FgaFO5c+kuAPNeeZCAKv5cMpbaZZUCOe4ZzKtfDCYc5YJwboJf0Krp/JTKES3P4g
            cuuXjWLbeIigkd2tGYE8e4Pw9OBo2U5hSRTRuOyK46AJJgWsWwaXfKYGuyg7g5eQ
            1zfeXeURqRH+LiaDYRTHfrvtKfBPRC40r4TbZvA6mxqsTyE4u7Hg/yU1Y5wZDsBS
            LiGiFqksii2XpTJBxjgsj2E7pbApqqqHhqxBmWfmYs/jnDkuCD4uk1IquynF/AvW
            W50QnMk6e2isFOauxayVJZCh1NSxIU6zx9KsmmiMwXaUtx0lI857bj1k+ut4CBx5
            R8qvGeOHKZRDee6QO8Uz2zUclXjY9rWgKwDKKPG1MJlKTg/6PoOCIAHAPowQMRU+
            xTR/Ba5ratgHdtHFO5nmZY3hwQ2rof21HujO+qscrQNlGwjRzhJx1KYAsAcCCeHS
            XgGuokLoWr/OIDSP2QrAjAEqjyl1ukaPLffqt2/9lvC/Oh/S2iLtH1mzIccpGa1Z
            dGTf0Quen/0Umg/b3TZKsqiGEXKPJECzChp6TgUOFBmHfARuaI2FYecsSNBSmtc=
            =tq9k
            -----END PGP MESSAGE-----
          fp: 84680C43E8FBE3DBA9468BD330D9BD1C5E315159
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
