---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  namespace: ceph
spec:
  namespaceSelector:
    matchNames:
      - ceph
  selector:
    matchLabels:
      app: csi-metrics
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 5s
