# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KMmgcyKciq7hsJWFGqFipA==,iv:wskuCk5ASfpc5bLbJtMi4sWkT/cAwWtpkVNVSo5a8wE=,tag:zU1hsYThw7cDzoAs25kOdQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:eqvWon6KKspyzwHi8L4gmjRZ5RpZwL81nUNMZidqYjUAR+vHyg==,iv:PaK1rtrbDPYCo1IlXbYPYmVTzF79oiBKu/MHBcWHWSw=,tag:qh/xcjKxhG01whbUqitImQ==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:hGmuvU/bXMfXhsCPfMlb6oXLk3VnS+xcB4KhC3DQC9E=,iv:1U/I7Izub48cGcPyx3a48cNSSrp3aMXuTsfT3Y9UzP8=,tag:/j+37M7t5BFeCSZtt6433Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:iHCiyIbI8DJYRc4WPAa+XaYH,iv:AzzNTRtbkCsRQos1Pvw2ghnEcs0LwmpvZJdPW+2G1fU=,tag:Q7Y8ABnVJzD65WwHPTr3ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-06T19:26:31Z"
    mac: ENC[AES256_GCM,data:YzIlfNKgSfwACB+hhj9CNbBSEiM9UJ5sXBZ0PNbKsdwikkmT4mYorPz88n4gm8uacojsY5UjTLL4vnLNFMLTxM+/jbLp8UMqhf0DEHFdQS5gtVXoB4qpGVaO+45nkQ0k+UfKBSbUdGIo02qGGu3JXefc8HY/e1ZP3lTasNNzsKU=,iv:EnuJHoXgW7nu0YxJ2l2sParTOLNQInsdk6gjYl9IIQQ=,tag:PLdRol4lJHDUCR0+rr3yJA==,type:str]
    pgp:
        - created_at: "2021-05-06T19:26:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/0I6bEV8DNNAQ/+Iquym2c+R4tu7mfRGNaSflRhqUfcQTmrNhC0jFxiAxwH
            rDG+7FSJOKr/A2yXnSsy34acCU85qS53AaAmXrddOdC5Gh7ksqXVOZFteCSOm23L
            t+G7nmI+FWiW09U81RXPNxB5goj0D1yOcrhwX5xFzoJT/phfa5gALNXkyH3NfKL2
            KwsglD85e9atzBBpIIWp4hjbTAVElmGkvGn83Rwi0jv0sbBv9+uo4dZCx1WAS2L+
            sgGs9/MB3KLjD0HeuDKWBU/eDC2zEv1PuZIrys03xinAS4NmYpkawL8l47+XiKDD
            OmPTLNYkrtXu7QCYn5xk/sgL/p8AukshUyqz5hHnQnRtoiZjdmOYcMx3BbBmSilt
            usR+t7Cv+BGsGj/SjY0rJvEtetH8iPn8LQaAesw6sXrVzPE/q7yqnCcHOgwCXO5m
            z6UYckphsxgn3Q36eEwXzScxI/SQYKPLcZgsRkvsmXJXZcMyhZKB6DMemlHalrzH
            k4WRodcWB8STExGsiOPJp34uMpM40Vyx8YsbU0T98u20OXAb4k/voPEB+BOhzgju
            HGvTCdWaOgeOLsA8bh5leNuVlp/caBGCHN9DbVPROMJgjf8T1FI3gEo3WT00DagI
            dr73nZqx8yIrXgV4gcGHzdV4NAXfiT9WyTFwd/aK9mxgs8xKrr0nI7Jb53ulB6vS
            XgE/Ce9PkM1y4WbPxWoKgxwvjA6BrqlCezR5GJsMYCeU70T4PUBwLBbRrYZ7HnhU
            F5aKCmv7QDomUJCNyCPT/ZMYAUnPTi/HYQp0RG8WMFmoVuDwMwMKrwR+rAXxIP4=
            =YNwn
            -----END PGP MESSAGE-----
          fp: 84680C43E8FBE3DBA9468BD330D9BD1C5E315159
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
