# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PNlTS/6KTD40DjNBDbJgjQ==,iv:q589FAkre91GJkDbFmjQJHbvxq7NoN7fJ78aOh2a4/E=,tag:Is9j2ywttYSJwgAUsIbHyg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:n0m0mgNe3ES+RONLiOBMd4GRDGnPUYCuZ3LEnOAoFiP7TiR1gA==,iv:NxCraRF6ZTznp/Vcyy7W7nLu1YAXE726/6OOkbZ57sE=,tag:+luxd4ehPI9ZeC8ZHqLXsQ==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:KMKRvNua4ADbz/GVLsWrhVM6lfEz3k9ceVM9SX0Xon8=,iv:9zqwgGGOQHQ201OYh+o+bERJG/oxPmFY9eD37l02nFI=,tag:b/0yq78Ljcr2Yu9gCxLv0Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:mdtl4VrT+lSDhf573M/fS0UE,iv:be8hXAllQjQl3XFeESphgUHTcZ7SaR5Y/8pT+3+hhrE=,tag:+UZDGh4LErkbBEFDekPLuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-01T00:28:29Z"
    mac: ENC[AES256_GCM,data:4nO+TDQqDrK+kk0T11yQvywIu9nv21FR35RkoTjHvO0qxDP/ATrcqNMj1m45+kVrOmiPREm4owaz0jMUS2mIUWVQgDvllPZxh4OVs8Fl6nGA6aHBcI50D/W52C5aoJwvad8jy09oyUVUVsWxfpwxb2yGwgaCZlCWiDlQZkMOsGU=,iv:2p+Vpd14oCwkHoCK7mjhCSWHvY7+5jtN8bvMOQ5ZxBM=,tag:7rvdqyYPd1BfCEVZKlfyBA==,type:str]
    pgp:
        - created_at: "2021-05-01T00:28:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/0I6bEV8DNNAQ//dGcIhMM9Z3b5TkPD2hRKQCTHksXfqFQckNku++ppb2tE
            90XJ635K4bIyfOHxoKV/0p0F7LgaO//jR6qcQmNOgaQv7YmaG3mSOl+m64UZCE4y
            LdtKdv/cj+LX/ZQEoBXaDBmlPfTpibQ4969z7sb0Bed9rKIQjnscMjSExk+aO1uJ
            wpp76/Y4zECaH4MHFEg6Jddkm/JRuTZB1ueiCsWa0Q4EoxJUnoS7WmQtEl9MVSqp
            0GlmkvHS7KzFt+0GjXb957WODE9aJjYRJEUic32J7W1sHf292EHpHk6x2bwAEbEc
            c2jo/aGgZD3RYmbAqkQWhaxErqIoeaZu3fXnr8ctev0znt06Kvlj9YqaVmgVTS+Y
            6nHx6Gqfjng1G4FFxjRFaig1GblCmkefqGC9qfkNU1dQuEhmtH+S4qkFWx5WRp96
            p+Uud2cJLjZC1deNUBnnmtXy/fjo0yeXHJo0yfJD46UVhOjGnYz76WTu7qyA/Mvr
            1YmlZzAuj3mX4PMHQMIuAlfp/7K5rvr4fahgsu+RSw4Jni3VR0ftx948HJDo7wri
            3Cg+F7A3GraBYtxSteWKzBoxqqJvKuti2FPWcjJdM1Ck6Am0ga+IaCKAXndVHPkx
            63NpxEmxb+n0UIhEP4AKQ0K6as5MeQ4E+MqcVZmnfUSIxH8IU9dKclXpFbdgTe3S
            XgHuhj6oj5xXRv6zxrjQer9J22BQE7iJR+M/+KFrRvhUAYwbrCHvKJ8vbVN5O/GI
            UPSc7YO/fbxOMPlv5gFPwKc/VgZPcIrffYKUfrM84yHOwnMs+NdQKUBV7MqF7n0=
            =KGHW
            -----END PGP MESSAGE-----
          fp: 84680C43E8FBE3DBA9468BD330D9BD1C5E315159
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
