---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: networking
spec:
  schedule: "0 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cloudflare-ddns
              image: curlimages/curl:7.76.1
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: cloudflare-ddns
              command:
                - "/bin/sh"
                - "/app/cloudflare-ddns.sh"
              volumeMounts:
                - name: cloudflare-ddns
                  mountPath: /app/cloudflare-ddns.sh
                  subPath: cloudflare-ddns.sh
                  readOnly: true
          volumes:
            - name: cloudflare-ddns
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: cloudflare-ddns
                      items:
                        - key: cloudflare-ddns.sh
                          path: cloudflare-ddns.sh
