---

# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s#agent-worker-configuration

# Don't define the host as control plane nodes
k3s_control_node: false

# k3s settings for all worker nodes
k3s_agent:
  # server: "https://192.168.1.1:6443"
  node-ip: "{{ ansible_host }}"
  kubelet-arg:
  - "feature-gates=GracefulNodeShutdown=true"
