---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.6.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: stable-fpm-alpine
      pullPolicy: IfNotPresent
    replicaCount: 1
    nextcloud:
      host: "nextcloud.${SECRET_CLUSTER_DOMAIN}"
      existingSecret:
        enabled: true
        secretName: nextcloud-creds
        usernameKey: "NEXTCLOUD_USERNAME"
        passwordKey: "NEXTCLOUD_PASSWORD"
        smtpUsernamekey: "NEXTCLOUD_SMTP_USERNAME"
        smtpPasswordkey: "NEXTCLOUD_SMTP_PASSWORD"
      datadir: "/var/www/html/data"
      mail:
        enabled: true
        fromAddress: "$NEXTCLOUD_SMTP_USERNAME"
        domain: "$NEXTCLOUD_SMTP_DOMAIN"
        mail:
          smtp:
            host: "$NEXTCLOUD_SMTP_HOST"
            secure: ssl
            port: 465
            authtype: LOGIN
            name: "$NEXTCLOUD_SMTP_USERNAME"
            password: "$NEXTCLOUD_SMTP_PASSWORD"
    internalDatabase:
      enabled: false
    mariadb:
      enabled: true
      db:
        name: "$NEXTCLOUD_DB_NAME"
        password: "$NEXTCLOUD_DB_PASSWORD"
        user: "$NEXTCLOUD_DB_USERNAME"
      rootUser:
        password: "$NEXTCLOUD_DB_ROOT_PASS"
    redis:
      enabled: true
    cronjob:
      enabled: true
    persistance:
      enabled: true
      storageClass: "ceph-rbd-sc"
      accessMode: ReadWriteOnce
      size: 8Gi
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "nc-rep,nc-header"
      hosts:
        - "nextcloud.${SECRET_CLUSTER_DOMAIN}"
      tls:
        - hosts:
            - "nextcloud.${SECRET_CLUSTER_DOMAIN}"
