---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: databases
spec:
  releaseName: mariadb
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 9.3.11
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 10.7.4-debian-10-r0
      pullPolicy: IfNotPresent
      debug: false
    clusterDomain: cluster.local
    architecture: replication
    auth:
      rootPassword: "${MARIADB_ROOT_PASSWORD}"
      replicationUser: mariadb-repl
      replicationPassword: "${MARIADB_REPLICATION_PASSWORD}"
    primary:
      persistence:
        enabled: true
        storageClass: "ceph-rbd-sc"
        accessModes:
          - ReadWriteOnce
        size: 8Gi
    secondary:
      replicaCount: 3
      persistence:
        enabled: true
        storageClass: "ceph-rbd-sc"
        accessModes:
          - ReadWriteOnce
        size: 8Gi
    volumePermissions:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/bitnami-shell
        tag: "10"
        pullPolicy: Always
    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mysqld-exporter
        tag: 0.12.1-debian-10-r430
        pullPolicy: IfNotPresent
