# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-creds
    namespace: databases
stringData:
    mariadb-replication-password: ENC[AES256_GCM,data:2fRg/SavSJ6DzuiVszqNj9YQmHjNIyiU,iv:yedhD9QfvSF72QvG+UcKsaA48fD5atgqxTac8kTvSxo=,tag:rgGqZMnUu5tSh2Jbqeewng==,type:str]
    mariadb-password: ENC[AES256_GCM,data:mA9dlpaO8KBJBNx+jhkvFIBuaatoK55E,iv:/63XmUu/Pq57fZGWRVGdf81s9Q3QfUGdo6eyWL7iQAE=,tag:XKHwKfmOadLjEoVDEqqKFw==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:mHgzJPHK+gtfZrsEV8plULG3/U8rnwvr,iv:8uiCtFXdUDSdpkEdJlDcfHx1nTDgYPxwVtnZ4aVkRhI=,tag:4Sp3T8r2pMtTJnHJrdoAAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-12T02:07:29Z"
    mac: ENC[AES256_GCM,data:tqZAL4wiGlunJCj7Kllo0cE9Fs8OGoeJzyyH2Wwc7CWOh+xV500tFfcTYnR+0QsQV9FRoA4/sS/91Smz6tdRwGjaX3iMfs6ApfyAA/VWGgg6nC2jiqyDPU6Q2Du3Y+il+HBqSOYOiFdGq+9uoa8Ua1fmWzyPzP83RNEXzvzjNo0=,iv:PtCdKHvHSDTO2GboB8M32NQv/0RitnShepk+PjvT8Cs=,tag:f3UhAH+CYuwSDKaskIWkGA==,type:str]
    pgp:
        - created_at: "2021-05-12T02:07:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/0I6bEV8DNNAQ/+N5bteidybxXLvPmBZsCyS7z9JlaPHkB6ypS5F7l4iNIu
            xZtPgV/s9WgIUks0upJYbXRKMerRZ4vsOOHcozitUbUoGAJsYMYkYsHmZKi2dMAb
            XG31WeYsEPYMKc7rDjiGEG4/Q4U1aELgcmqDld7kQYGmskb76+IQOFJNAbRyvC1V
            0o+RWNqTS0V+Y2/2o3jLaNEEOoWLdZ31uVJBqKTcJEZW3uoeIPys+RyjMVjsNYM7
            HHmMsDR/TQ4dnOXavvMkm7poz91+ADotMOFLqyuklpgXuKqVOe3nnhgYhTG5VhlO
            N3OOhJWuDlq65uYGjoJ8PRxdIHO+jXjvfJyFTJS5Rn4xUWaiW6NHQuknl8iu2p4h
            gqpmMy+/bvAzVA1OAhKcd3L4WgYoJqganYTGyw1m4iN8uJ25Ho9dIeVwYoDWDHLX
            1+OOuLjCO5qNmFbynpFXZuhs6+ayyWHdoE+Bt+KizxNBYJwq9HSUvd83Idpo5sc+
            Po6mqYpNlC8zZGXhrstsOYhBb8hyKugl2K/z7Nv+DYrbcxFflgKxw6ZQ198NX3oq
            69hqA0A0GOnli2OpKLUPed/k63rhcuD5Wki2YzVLDx4TZlD/jNdxMZoa1AKF7kDK
            CntOOR6yn5sDIJ3GF8DfbudTVwNzjhyhk1nI0d/7PFbr6I2Q1roJZNWZyUGnlPPS
            XAHaUlrREylIvN6spR2h+ODft1Z+ScusDGgGjBky7XcYOYf5DPGCjb5G4UketwJX
            SzON8y8vCLjtlGc1dpid1NdIEsNI3Y693UWy7BAmUSTlU602umIZ01CHlKgy
            =PwHl
            -----END PGP MESSAGE-----
          fp: 84680C43E8FBE3DBA9468BD330D9BD1C5E315159
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
