---
# Use Calico CNI driver
calico:
  enabled: true
  operator_manifest: "https://docs.projectcalico.org/manifests/tigera-operator.yaml"
  # Enabling BGP requires your router set up to handle it
  bgp:
    enabled: false
    # peer is usually your router e.g. 192.168.1.1
    peer: 192.168.4.1
    as: 64512
    # externalIPs is the network you want services to consume
    # this network should not exist or be defined anywhere in your network
    # e.g. 192.168.169.0/24
    externalIPs: 192.168.69.0/24
