# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Uokd9uPK0jD7ULZaUOI2TbBmkrLV0vkfALo89Y2OeviUABxVizzNXSo6ROklnwkXaySpZ5rnwlX/eaEDO5tEosZpyOhdnTGb+9bgdHbghljVT+QW/o2pCxm0RfmnFg4FQuiGTcGwGea8jPd4ncRTjRuLTVvpx9UV,iv:GKdY5YmfS2ToI23fnVyTEhJml3/fF0o7UCjIEwdKK2A=,tag:3eFKpIc18NpTCoIxAXsEqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-27T02:56:47Z"
    mac: ENC[AES256_GCM,data:4+eWAmmcJvKDza6zN2RjdF1fchzBALV0s0qszko2/Y6vn9udHxeJJjTs4P3rGDDPx5GhX1d2Pn9lNl5txjdANexJP5Z5ZCYTouV6gT3WihZR3rhHIR4b+FkWeCYk04duspP0JzYsE3a4KeJCzs+W0IybNcyGrxzGvVE9PJPzVzM=,iv:wOvLYAyQug5pqr6V3/bV4Q0DWQj4W2TRYsp+EDPpC2Q=,tag:cZ0NmAYutaBVAmQeaHd5HQ==,type:str]
    pgp:
        - created_at: "2021-04-27T02:56:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/0I6bEV8DNNAQ//YA2GpSUH4Haa5GvXtc89FdixcfCq+k5n4YTpPlnnw7uy
            yvD0xjBTMpMyNIsuZJzDQNUYtC5TLikRlzr3nGEJs65v1OZr9JdpJLr2FcwmIIyU
            6xS1jMRqk6536rSQb896Jg4s7Ua0Pjgp5B3gBkawBXDN0G3jC3DMOPP8pLm1Oomd
            eQthToRAAjo/oVEhOyx5tq55JFXFQun2UHHW1HLqQ7oI58BQgDUyVwYMt5kz4Wj0
            e3GYZVVwNi9j7fDpaoLhlSTDm2+cjnH7SlwGLHor5rnOy6piFiPuT2Nw4RSvXYQN
            jNx8Ccl+zRiqXQuWrfXs90seRUQGh5DraBxG2wFXdvl1NtNhLQPQt8U9SHn7xLlw
            0VAs3k6bsSgPJGX+s0t4YKhs2idylhCsOCsxgYLiZBC5fH78/rSMCgHEboo0+6jF
            ayD3JOLUlCOi3zP7QAYjlI7WT44IytY2yI4OEsRBwYWt93YG4xWHdUdC4vEgaFH/
            +uHEQO4n6ZNEcSa64haWwLBlE97xppdWbbMFL+hAZB1FaeFIibZUm5PUAnn+lMxq
            L8rMyMEnPDrWrRRexubvTD8JMI0reFp5Hyj5YWlaJSo6+mB7kNn798Gti9D8faIk
            WWfXrXIP0Io7M6Smz0QEHdD01BBswpiY47kNbXi0onpSYWfClh2pFOM/SYGKYD/S
            XAFmwD79rkFUEFIjw1LfGYt391F69onHqZZZj5NOULia1Z0sWLnKOAABHC3Is9et
            z7QRbv2BuYFF0WfN2yLqpo6vWwtfb8fK388YI9un8WWL0/1sAV3LqL2ixdv1
            =e4Vn
            -----END PGP MESSAGE-----
          fp: 84680C43E8FBE3DBA9468BD330D9BD1C5E315159
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.7.1
