---
- hosts:
    - control-nodes
    - generic-nodes
  become: true
  gather_facts: true
  vars_prompt:
    - name: "run_confirmation"
      prompt: "This will DESTROY your cluster. Do you wish to continue? [Y/n]"
      default: "n"
      private: false
  any_errors_fatal: true
  pre_tasks:
    - name: check confirmation
      fail:
        msg: "Abort."
      when: run_confirmation != "Y"
  tasks:
    - name: kill k3s
      ansible.builtin.command: /usr/local/bin/k3s-killall.sh
    - name: uninstall k3s
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-uninstall.sh
        removes: /usr/local/bin/k3s-uninstall.sh
    - name: uninstall k3s agent
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-agent-uninstall.sh
        removes: /usr/local/bin/k3s-agent-uninstall.sh
    - name: gather list of CNI files to delete
      find:
        paths: /etc/cni/net.d
        patterns: "*"
      register: files_to_delete
    - name: delete CNI files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"
    - name: reboot
      ansible.builtin.reboot:
        msg: "Nodes are being rebooted..."
      ignore_errors: true
