---
apiVersion: v1
kind: Secret
metadata:
  name: k10-s3-secret
  namespace: kasten-io
type: secrets.kanister.io/aws
stringData:
  aws_access_key_id: ${SECRET_K10_S3_ACCESS_KEY_ID}
  aws_secret_access_key: ${SECRET_K10_S3_SECRET_KEY}
