---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: wasabi-s3
  namespace: kasten-io
spec:
  locationSpec:
    type: ObjectStore
    objectStore:
      endpoint: s3.us-east-1.wasabisys.com
      name: ${SECRET_S3_BUCKET}
      objectStoreType: S3
      pathType: Directory
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: k10-s3-secret
        namespace: kasten-io
  type: Location
