---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  # Router Gateway IP
  GATEWAY_IP: "10.0.27.1"
  #Available IP range for Load Balancer services
  METALLB_ARP_RANGE: "192.168.4.101-192.168.4.120"
  # Loadbalancer IPs
  LB_COREDNS_IP: "192.168.4.101"          #CLUSTER_LB_COREDNS: "192.168.69.180"
  LB_TRAEFIK_IP: "192.168.4.102"          #CLUSTER_LB_TRAEFIK: "192.168.69.200"
  LB_BLOCKY_IP: "192.168.4.103"           #CLUSTER_LB_BLOCKY: "192.168.69.115"
  LB_HOME_ASSISTANT_IP: "192.168.4.104"
  LB_PLEX_IP: "192.168.4.105"
  LB_QBITTORRENT_IP: "192.168.4.106"
  LB_RTORRENT_FLOOD_IP: "192.168.4.107"
  LB_LOKI_IP: "192.168.4.108"             #CLUSTER_LB_LOKI: "192.168.69.110"
  LB_VERNEMQ_IP: "192.168.4.109"
