---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_LB_INGRESS_EXTERNAL: "192.168.69.100"
  CLUSTER_LB_INGRESS_INTERNAL: "192.168.69.101"
  CLUSTER_LB_LOKI: "192.168.69.110"
  CLUSTER_LB_COREDNS: "192.168.69.180"
  CLUSTER_LB_TRAEFIK: "192.168.69.200"
  CLUSTER_LB_BLOCKY: "192.168.69.115"
