---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  releaseName: postgresql
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 11.11.0-debian-10-r86
      pullPolicy: IfNotPresent
    volumePermissions:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/bitnami-shell
        tag: "11"
        pullPolicy: Always
    replication:
      enabled: true
      user: repl_user
      password: "${POSTGRESQL_REPLICATION_PASSWORD}"
      readReplicas: 2
      synchronousCommit: 'off'
      numSynchronousReplicas: 0
    postgresqlUsername: postgres
    postgresqlPassword: "${POSTGRESQL_PASSWORD}"
    postgresqlDataDir: /bitnami/postgresql/data
    persistence:
      enabled: true
      mountPath: /bitnami/postgresql
      accessModes:
        - ReadWriteOnce
      size: 8Gi
    metrics:
      enabled: false
    readReplicas:
      persistence:
        enabled: false
