---
- name: kernel | enable modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - nf_conntrack
    - overlay
    - rbd
    - ip_vs
    - iscsi_tcp
  when:
    - molecule_is_test is defined and not molecule_is_test

- name: kernel | enable modules on boot
  become: true
  ansible.builtin.copy:
    mode: 0644
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  loop:
    - br_netfilter
    - overlay
    - rbd
    - ip_vs
    - iscsi_tcp
  when:
    - molecule_is_test is defined and not molecule_is_test
