---
- name: unattended-upgrades | delete 20auto-upgrades config
  become: true
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    state: absent

- name: unattended-upgrades | copy 10periodic config
  become: true
  ansible.builtin.copy:
    mode: 0644
    src: unattended-upgrades-10periodic
    dest: /etc/apt/apt.conf.d/10periodic

- name: unattended-upgrades | copy 50unattended-upgrades config
  become: true
  ansible.builtin.copy:
    mode: 0644
    src: unattended-upgrades-50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: unattended-upgrades | start systemd service
  become: true
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

- name: unattended-upgrades | restart systemd service
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted
