---
- name: user | get home directory
  ansible.builtin.shell: "echo $HOME"
  changed_when: false
  check_mode: no
  register: user_home

- name: user | add to sudoers
  become: true
  ansible.builtin.copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: "0440"

- name: user | add additional SSH public keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  loop: "{{ ssh_authorized_keys }}"
  when:
    - ssh_authorized_keys is defined
    - ssh_authorized_keys is iterable
    - ssh_authorized_keys | length > 0

- name: user | check if hushlogin exists
  ansible.builtin.stat:
    path: "/{{ user_home.stdout }}/.hushlogin"
  register: hushlogin_result

- name: user | silence the login prompt
  ansible.builtin.file:
    dest: "/{{ user_home.stdout }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: "0775"
  when: not hushlogin_result.stat.exists

- name: user | create config directory
  ansible.builtin.file:
    path: "/{{ user_home.stdout }}/.config"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    mode: "0775"

- name: user | create neofetch directory
  ansible.builtin.file:
    path: "/{{ user_home.stdout }}/.config/neofetch"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    mode: "0775"

- name: user | copy neofetch configuration
  ansible.builtin.copy:
    owner: "{{ ansible_user }}"
    mode: "0775"
    src: user-neofetch-config.conf
    dest: "/{{ user_home.stdout }}/.config/neofetch/config.conf"

- name: user | copy ascii art
  ansible.builtin.copy:
    owner: "{{ ansible_user }}"
    mode: "0775"
    src: user-neofetch.art
    dest: "/{{ user_home.stdout }}/.config/neofetch/k8s.art"

- name: user | enable neofetch on login
  ansible.builtin.copy:
    content: "neofetch --source /{{ user_home.stdout }}/.config/neofetch/k8s.art --ascii_colors 5 --colors 5 --separator ' :'"
    dest: "/{{ user_home.stdout }}/.bash_profile"
    owner: "{{ ansible_user }}"
    mode: "0775"
