---
- hosts:
    - control-nodes
    - generic-nodes
  become: true
  gather_facts: true
  vars_prompt:
    - name: "restart_confirmation"
      prompt: "Restart nodes when complete? [Y/n]"
      default: "n"
      private: false
  tasks:
    - name: upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        cache_valid_time: 3600
        autoclean: true
        autoremove: true
      register: apt_upgrade
      retries: 5
      until: apt_upgrade is success
    - name: reboot
      ignore_errors: true
      ansible.builtin.reboot:
        msg: "Nodes are being rebooted..."
      when: restart_confirmation == "Y"
      tags:
        - always
