---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_CLUSTER_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${SECRET_CLUSTER_DOMAIN/./-}-tls"
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_CLUSTER_DOMAIN}"
  dnsNames:
    - "${SECRET_CLUSTER_DOMAIN}"
    - "*.${SECRET_CLUSTER_DOMAIN}"
