
---

- hosts:
  - master-nodes
  - worker-nodes
  # - storage
  become: true
  gather_facts: true
  tasks:

  #
  # Turn off master-nodes and worker-nodes devices in 2 minutes
  #

  - name: turn off master-nodes
    # ansible.builtin.command: /sbin/shutdown -h 2
    ansible.builtin.command: /sbin/shutdown --help
    when: "'master-nodes' in group_names"

  - name: turn off worker-nodes
    # ansible.builtin.command: /sbin/shutdown -h 2
    ansible.builtin.command: /sbin/shutdown --help
    when: "'worker-nodes' in group_names"

  #
  # Turn off NAS devices in 5 minutes
  #

  # # Qnap devices do not have /sbin/shutdown and
  # # instead use busybox /sbin/poweroff
  # - name: turn off storage nodes
  #   # ansible.builtin.command: /sbin/poweroff -d 300
  #   ansible.builtin.command: /sbin/poweroff --help
  #   when: inventory_hostname == "nas-rocinante"

  # - name: turn off storage nodes
  #   # ansible.builtin.command: /sbin/shutdown -h 5
  #   ansible.builtin.command: /sbin/shutdown --help
  #   when: inventory_hostname == "nas-serenity"
