---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io/
      chart: k10
      version: 5.5.11
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    eula:
      accept: true
      company: "${SECRET_CLUSTER_DOMAIN}"
      email: "${SECRET_EMAIL}"
    global:
      persistence:
        storageClass: ceph-rbd-sc
    auth:
      tokenAuth:
        enabled: true
    prometheus:
      enabled: true
      server:
        persistentVolume:
          enabled: false
    clusterName: k8s
    ingress:
      create: true
      host: "k10.${SECRET_CLUSTER_DOMAIN}"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      urlPath: k10
      hosts:
        - "k10.${SECRET_CLUSTER_DOMAIN}"
      tls:
        enabled: true
        secretName: "${SECRET_CLUSTER_DOMAIN/./-}-tls"
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Ingress
              name: k10-ingress
            patch:
              - op: add
                path: /spec/ingressClassName
                value: traefik
